import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo as ArchivoFont } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/constants/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = ArchivoFont({
  variable: "--font-archivo",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Diagno✘is (DX)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}
      >
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
